name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧹 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'documentation'
template: |
  ## 🎉 BCRDF v$RESOLVED_VERSION

  $CHANGES

  ### 📦 Binaries disponibles

  **Linux:**
  - `bcrdf-linux-x64.tar.gz` - Linux x64
  - `bcrdf-linux-arm64.tar.gz` - Linux ARM64
  - `bcrdf-linux-x32.tar.gz` - Linux x32

  **Windows:**
  - `bcrdf-windows-x64.zip` - Windows x64
  - `bcrdf-windows-arm64.zip` - Windows ARM64
  - `bcrdf-windows-x32.zip` - Windows x32

  **macOS:**
  - `bcrdf-darwin-x64.tar.gz` - macOS x64
  - `bcrdf-darwin-arm64.tar.gz` - macOS ARM64

  ### 🚀 Installation

  ```bash
  # Linux/macOS
  tar -xzf bcrdf-linux-x64.tar.gz
  sudo mv bcrdf /usr/local/bin/

  # Windows
  # Extraire le zip et ajouter au PATH
  ```

  ### 📋 Changelog

  Consultez les [commits](https://github.com/$GITHUB_REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION) pour les détails.

  ### 🔐 Sécurité

  - Chiffrement AES-256-GCM et XChaCha20-Poly1305
  - Compression GZIP configurable
  - Déduplication basée sur SHA-256
  - Compatible S3 (AWS, Scaleway, OVH, etc.)

  ### 📚 Documentation

  - [Guide d'installation](https://github.com/$GITHUB_REPOSITORY#installation)
  - [Exemples d'utilisation](https://github.com/$GITHUB_REPOSITORY/blob/main/docs/EXAMPLES.md)
  - [Architecture](https://github.com/$GITHUB_REPOSITORY/blob/main/docs/ARCHITECTURE.md) 