run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - gocyclo
    - dupl

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  gosec:
    excludes:
      - G101  # Look for hardcoded credentials
      - G204  # Subprocess launched with variable

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl 