storage:
    type: s3
    bucket: webserver
    region: fr-par
    endpoint: https://s3.fr-par.scw.cloud
    access_key: SCWQYGZR960ZKMR7AVZK
    secret_key: 39ea277b-ea9e-40b6-a515-d11975343838
    storage_class: GLACIER
    username: ""
    password: ""
backup:
    encryption_key: 1298405cf83af6acb39679a4c64eeb14a0d1a82faef3ebf9d64fd9652a0595bf
    encryption_algo: aes-256-gcm
    compression_level: 1
    max_workers: 16
    checksum_mode: fast
    buffer_size: 32MB
    batch_size: 25
    batch_size_limit: 8MB
    skip_patterns:
        - '*.tmp'
        - '*.cache'
        - '*.log'
        - .DS_Store
        - Thumbs.db
        - '*.swp'
        - '*.swo'
        - node_modules/
        - .git/
        - __pycache__/
        - '*.zip'
        - '*.tar.gz'
        - '*.rar'
        - '*.7z'
        - '*.iso'
        - '*.vmdk'
        - '*.vdi'
        - '*.qcow2'
        - '*.raw'
    chunk_size: 32MB
    memory_limit: 256MB
    network_timeout: 120
    retry_attempts: 5
    retry_delay: 2
    cache_enabled: true
    cache_max_size: 10000
    cache_max_age: 60
    compression_adaptive: true
    sort_by_size: true
    chunk_size_large: 50MB
    large_file_threshold: 100MB
    ultra_large_threshold: 1GB
retention:
    days: 30
    max_backups: 10