# BCRDF Configuration Example - WebDAV Storage
# Example configuration for WebDAV server (Nextcloud, ownCloud, etc.)

storage:
  type: "webdav"
  # WebDAV server URL (examples for different services)
  endpoint: "https://your-nextcloud.com/remote.php/dav/files/username/"
  # endpoint: "https://your-owncloud.com/remote.php/webdav/"
  # endpoint: "https://webdav.example.com/dav/"
  
  # WebDAV credentials
  username: "YOUR_USERNAME"
  password: "YOUR_PASSWORD"
  
  # S3 fields (unused for WebDAV)
  bucket: ""
  region: ""
  access_key: ""
  secret_key: ""

backup:
  # Encryption key (32 bytes in hexadecimal) - generate a new one!
  encryption_key: "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
  encryption_algo: "aes-256-gcm"  # Options: "aes-256-gcm", "xchacha20-poly1305"
  compression_level: 3  # GZIP level (1-9)
  max_workers: 32  # Number of parallel workers (optimized for performance)
  checksum_mode: "fast"  # Options: "full" (slow, secure), "fast" (recommended), "metadata" (fastest)
  buffer_size: "64MB"  # Buffer size for I/O operations
  batch_size: 50  # Number of small files to batch together (performance optimization)
  batch_size_limit: "10MB"  # Maximum size for batch uploads
  
  # Advanced performance optimizations
  chunk_size: "64MB"  # Chunk size for streaming compression/decompression
  memory_limit: "512MB"  # Memory limit for processing large files
  network_timeout: 300  # Network timeout in seconds (5 minutes)
  retry_attempts: 3  # Number of retry attempts for failed uploads
  retry_delay: 5  # Delay between retries in seconds
  
  # Phase 1 performance optimizations
  cache_enabled: true  # Enable checksum caching for faster processing
  cache_max_size: 10000  # Maximum number of cached checksums
  cache_max_age: 60  # Cache entry max age in minutes
  compression_adaptive: true  # Enable adaptive compression based on file size
  
  skip_patterns:  # Patterns to skip during backup (performance optimization)
    - "*.tmp"
    - "*.cache" 
    - "*.log"
    - ".DS_Store"
    - "Thumbs.db"
    - "*.swp"
    - "*.swo"
    - "node_modules/"
    - ".git/"
    - "__pycache__/"
    - "*.zip"
    - "*.tar.gz"
    - "*.rar"
    - "*.7z"
    - "*.iso"
    - "*.vmdk"
    - "*.vdi"
    - "*.qcow2"
    - "*.raw"

retention:
  days: 30
  max_backups: 10

# Popular WebDAV endpoint examples:
#
# Nextcloud: https://your-nextcloud.com/remote.php/dav/files/username/
# ownCloud:  https://your-owncloud.com/remote.php/webdav/
# Box.com:   https://dav.box.com/dav/
# 4shared:   https://webdav.4shared.com/
# pCloud:    https://webdav.pcloud.com/
#
# Note: Replace 'username' with your actual username