# Configuration BCRDF optimisée pour serveur web
# Spécialement conçue pour réduire l'usage CPU et accélérer les backups

storage:
  type: "s3"
  bucket: "bcrdf"
  region: "fr-par"
  endpoint: "https://s3.fr-par.scw.cloud"
  access_key: "SCW1M0G9HGMXR54XA46M"
  secret_key: "c0daf30e-3c70-4894-ab1b-c0c7d041d267"

backup:
  # === CHIFFREMENT ===
  encryption_key: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
  encryption_algo: "aes-256-gcm"
  
  # === OPTIMISATIONS CPU (CRITIQUES) ===
  max_workers: 1         # UN SEUL WORKER pour éviter la surcharge CPU
  compression_level: 1   # Compression la plus rapide
  checksum_mode: "metadata"  # Mode le plus rapide (10x plus rapide que "fast")
  
  # === BUFFERS MINIMAUX ===
  buffer_size: "4MB"     # Buffer très petit
  batch_size: 5          # Très peu de fichiers par batch
  batch_size_limit: "2MB" # Limite très petite
  
  # === CHUNKING OPTIMISÉ ===
  chunk_size: "8MB"      # Chunks très petits
  memory_limit: "64MB"   # Très peu de mémoire
  chunk_size_large: "5MB"
  large_file_threshold: "25MB"      # Seuil très bas
  ultra_large_threshold: "100MB"    # Seuil très bas
  
  # === RÉSEAU OPTIMISÉ ===
  network_timeout: 30    # Timeout court
  retry_attempts: 2      # Peu de tentatives
  retry_delay: 10        # Délai long entre tentatives
  
  # === OPTIMISATIONS ===
  sort_by_size: true     # Traiter les petits fichiers en premier
  compression_adaptive: true  # Ignore les fichiers déjà compressés
  
  # === FICHIERS À IGNORER (EXTENSIF) ===
  skip_patterns:
    # Fichiers système
    - "*.tmp"
    - "*.cache"
    - "*.log"
    - "*.temp"
    - ".DS_Store"
    - "Thumbs.db"
    - "*.bak"
    - "*.backup"
    - "*.old"
    - "*.swp"
    - "*.swo"
    - "*~"
    
    # Répertoires système
    - ".git/"
    - ".svn/"
    - ".hg/"
    - "node_modules/"
    - ".npm/"
    - ".cache/"
    - "__pycache__/"
    - ".pytest_cache/"
    - ".coverage"
    - ".tox/"
    - ".venv/"
    - "venv/"
    - "env/"
    - ".env/"
    
    # Fichiers compressés
    - "*.zip"
    - "*.tar.gz"
    - "*.tar.bz2"
    - "*.rar"
    - "*.7z"
    - "*.bz2"
    - "*.xz"
    - "*.gz"
    
    # Images disque
    - "*.iso"
    - "*.vmdk"
    - "*.vdi"
    - "*.qcow2"
    - "*.raw"
    - "*.img"
    
    # Médias
    - "*.mp4"
    - "*.avi"
    - "*.mkv"
    - "*.mov"
    - "*.wmv"
    - "*.flv"
    - "*.webm"
    - "*.jpg"
    - "*.jpeg"
    - "*.png"
    - "*.gif"
    - "*.bmp"
    - "*.tiff"
    - "*.pdf"
    
    # Logs système (CRITIQUE)
    - "/var/log/*"
    - "/tmp/*"
    - "/var/tmp/*"
    - "/var/cache/*"
    - "/var/spool/*"
    - "/proc/*"
    - "/sys/*"
    - "/dev/*"
    - "/run/*"
    
    # Fichiers web
    - "*.log"
    - "access.log"
    - "error.log"
    - "*.pid"
    - "*.lock"
    - ".htaccess"
    - "robots.txt"
    - "sitemap.xml"
    
    # Base de données
    - "*.db"
    - "*.sqlite"
    - "*.sqlite3"
    - "*.mysql"
    - "*.postgresql"

retention:
  days: 30
  max_backups: 3        # Très peu de sauvegardes à garder
