# BCRDF Configuration Example - S3 Storage
storage:
  type: "s3"
  bucket: "my-backup-bucket"
  region: "eu-west-3"
  endpoint: "https://s3.eu-west-3.amazonaws.com"
  access_key: "YOUR_ACCESS_KEY"
  secret_key: "YOUR_SECRET_KEY"
  # WebDAV fields (unused for S3)
  username: ""
  password: ""

backup:
  encryption_key: "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"  # 32 bytes hex for AES-256-GCM and XChaCha20
  encryption_algo: "aes-256-gcm"  # Options: "aes-256-gcm", "xchacha20-poly1305"
  compression_level: 1  # GZIP level (1-9) - Fastest to avoid compression issues
  max_workers: 16  # Number of parallel workers (balanced for stability)
  checksum_mode: "fast"  # Options: "full" (slow, secure), "fast" (recommended), "metadata" (fastest)
  buffer_size: "32MB"  # Buffer size for I/O operations (smaller for stability)
  batch_size: 25  # Number of small files to batch together (balanced)
  batch_size_limit: "8MB"  # Maximum size for batch uploads (smaller for stability)
  
  # Advanced performance optimizations
  chunk_size: "32MB"  # Chunk size for streaming compression/decompression (smaller for stability)
  memory_limit: "256MB"  # Memory limit for processing large files (reduced for stability)
  network_timeout: 120  # Network timeout in seconds (2 minutes)
  retry_attempts: 5  # Number of retry attempts for failed uploads (increased for stability)
  retry_delay: 2  # Delay between retries in seconds (faster retries)
  
  # Phase 1 performance optimizations
  cache_enabled: true  # Enable checksum caching for faster processing
  cache_max_size: 10000  # Maximum number of cached checksums
  cache_max_age: 60  # Cache entry max age in minutes
  compression_adaptive: true  # Enable adaptive compression based on file size
  sort_by_size: true  # Sort files by size (smallest first) for better UX
  
  skip_patterns:  # Patterns to skip during backup (performance optimization)
    - "*.tmp"
    - "*.cache"
    - "*.log"
    - ".DS_Store"
    - "Thumbs.db"
    - "*.swp"
    - "*.swo"
    - "node_modules/"
    - ".git/"
    - "__pycache__/"
    - "*.zip"
    - "*.tar.gz"
    - "*.rar"
    - "*.7z"
    - "*.iso"
    - "*.vmdk"
    - "*.vdi"
    - "*.qcow2"
    - "*.raw"

retention:
  days: 30  # Retention period in days
  max_backups: 10  # Maximum number of backups

# Popular S3-compatible services:
# 
# AWS S3:
#   endpoint: "https://s3.region.amazonaws.com"
#   region: "us-east-1", "eu-west-1", etc.
#
# Scaleway:
#   endpoint: "https://s3.fr-par.scw.cloud"
#   region: "fr-par", "nl-ams", etc.
#
# DigitalOcean Spaces:
#   endpoint: "https://region.digitaloceanspaces.com"
#   region: "nyc3", "fra1", etc.
#
# MinIO:
#   endpoint: "https://your-minio-server.com"
#   region: "us-east-1" (or any value)