# Configuration BCRDF pour Scaleway S3 Glacier
# ============================================
# Optimisée pour l'archivage longue durée avec coûts réduits

storage:
  type: "s3"
  
  # === SCALEWAY S3 GLACIER ===
  endpoint: "https://s3.fr-par.scw.cloud"
  region: "fr-par"
  bucket: "your-glacier-bucket"
  access_key: "your-access-key"
  secret_key: "your-secret-key"
  
  # Classe de stockage Glacier pour archivage longue durée
  storage_class: "GLACIER"  # Archivage longue durée, coûts réduits
  
  # Autres options Scaleway :
  # storage_class: "STANDARD"        # Stockage standard (accès immédiat)
  # storage_class: "DEEP_ARCHIVE"    # Archivage très longue durée (moins cher)
  # storage_class: "INTELLIGENT_TIERING"  # Optimisation automatique

backup:
  # === CRYPTAGE ===
  encryption_key: "your-32-byte-encryption-key-here"
  encryption_algo: "xchacha20-poly1305"  # Optimisé pour les performances
  
  # === COMPRESSION OPTIMISÉE POUR GLACIER ===
  compression_level: 6                    # Compression plus agressive pour économiser
  compression_adaptive: true              # Compression adaptative
  
  # === PERFORMANCE ADAPTÉE ===
  max_workers: 10                        # Moins de workers pour Glacier (latence)
  buffer_size: "64MB"                    # Buffer plus grand pour compenser la latence
  memory_limit: "512MB"                  # Plus de mémoire pour les gros fichiers
  
  # === CHUNKING OPTIMISÉ ===
  chunk_size: "64MB"                     # Chunks plus grands pour Glacier
  chunk_size_large: "100MB"              # Gros chunks pour gros fichiers
  large_file_threshold: "200MB"          # Seuil plus élevé
  ultra_large_threshold: "10GB"          # Seuil très élevé
  
  # === RÉSEAU ADAPTÉ ===
  network_timeout: 300                   # Timeout plus long pour Glacier
  retry_attempts: 8                      # Plus de tentatives
  retry_delay: 5                         # Délai plus long entre tentatives
  
  # === VÉRIFICATION OPTIMISÉE ===
  checksum_mode: "fast"                  # Vérification rapide
  cache_enabled: true                    # Cache des checksums
  cache_max_size: 15000                 # Cache plus grand
  cache_max_age: 120                    # Cache plus longtemps
  
  # === OPTIMISATIONS POUR ARCHIVAGE ===
  sort_by_size: true                     # Traiter les petits fichiers en premier
  batch_size: 100                       # Batch plus grand
  batch_size_limit: "16MB"              # Limite plus élevée
  
  # === EXCLUSIONS POUR ARCHIVAGE ===
  skip_patterns:
    - "*.tmp"
    - "*.cache"
    - "*.log"
    - ".DS_Store"
    - "Thumbs.db"
    - "*.swp"
    - "*.swo"
    - "node_modules/"
    - ".git/"
    - "__pycache__/"
    - "*.zip"
    - "*.tar.gz"
    - "*.rar"
    - "*.7z"
    - "*.iso"
    - "*.vmdk"
    - "*.vdi"
    - "*.qcow2"
    - "*.raw"
    - "*.mp4"                           # Vidéos (généralement déjà compressées)
    - "*.avi"
    - "*.mkv"
    - "*.mov"
    - "*.jpg"                           # Images (généralement déjà compressées)
    - "*.jpeg"
    - "*.png"
    - "*.gif"
    - "*.mp3"                           # Audio (généralement déjà compressé)
    - "*.wav"
    - "*.flac"

retention:
  days: 365                             # Archivage longue durée (1 an)
  max_backups: 50                       # Plus de backups pour l'archivage

# === NOTES IMPORTANTES POUR GLACIER ===
# 
# 1. LATENCE : Glacier a une latence élevée (3-5 heures pour restauration)
# 2. COÛTS : Beaucoup moins cher que le stockage standard
# 3. ACCÈS : Pas d'accès direct, nécessite une restauration temporaire
# 4. UTILISATION : Idéal pour les backups de sauvegarde, archives légales, etc.
# 
# === RESTAURATION DEPUIS GLACIER ===
# 
# Pour restaurer depuis Glacier :
# 1. Les objets sont automatiquement restaurés lors du téléchargement
# 2. La restauration peut prendre 3-5 heures
# 3. Les objets restaurés sont temporaires (1-7 jours selon la classe)
# 4. Utilisez la commande : bcrdf restore -n backup-name -d destination
